/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lyman_audioplayer_MainActivity */

#ifndef _Included_com_lyman_audioplayer_MainActivity
#define _Included_com_lyman_audioplayer_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lyman_audioplayer_MainActivity
 * Method:    createEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lyman_audioplayer_MainActivity_createEngine
  (JNIEnv *, jclass);

/*
 * Class:     com_lyman_audioplayer_MainActivity
 * Method:    createBufferQueueAudioPlayer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_lyman_audioplayer_MainActivity_createBufferQueueAudioPlayer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_lyman_audioplayer_MainActivity
 * Method:    setPlayingAssetAudioPlayer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_lyman_audioplayer_MainActivity_setPlayingAssetAudioPlayer
  (JNIEnv *, jclass, jboolean);

jboolean Java_com_lyman_audioplayer_MainActivity_createAssetAudioPlayer(JNIEnv* , jclass ,
                                                                        jobject , jstring);
#ifdef __cplusplus
}
#endif
#endif
