/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lyman_videoplayer_PngPreviewController */

#ifndef _Included_com_lyman_videoplayer_PngPreviewController
#define _Included_com_lyman_videoplayer_PngPreviewController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lyman_videoplayer_PngPreviewController
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_lyman_videoplayer_PngPreviewController_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_lyman_videoplayer_PngPreviewController
 * Method:    setSurface
 * Signature:
 */
JNIEXPORT void JNICALL Java_com_lyman_videoplayer_PngPreviewController_setSurface
        (JNIEnv *, jobject, jobject);


/*
 * Class:     com_lyman_videoplayer_PngPreviewController
 * Method:    resetSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_lyman_videoplayer_PngPreviewController_resetSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_lyman_videoplayer_PngPreviewController
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lyman_videoplayer_PngPreviewController_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
